AWSTemplateFormatVersion: "2010-09-09"
Mappings: 
  RegionMap: 
    us-east-1: 
      AMI: "ami-087bd41c05dfea1b9"
      TestAz: "us-east-1a"
    us-west-2: 
      AMI: "ami-a0cfeed8"
      TestAz: "us-west-2a"
Parameters: 
  EnvType: 
    Description: Environment type.
    Default: test
    Type: String
    AllowedValues: 
      - prod
      - test
    ConstraintDescription: must specify prod or test.
Resources:
  OTCSADM: 
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: m5d.xlarge
      KeyName: mackey
  MountPoint1: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSADM
      VolumeId: 
        !Ref app
      Device: /dev/sdf
  MountPoint2: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSADM
      VolumeId: 
        !Ref csefs
      Device: /dev/sdg
  MountPoint3: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSADM
      VolumeId: 
        !Ref csindex
      Device: /dev/sdh
  app: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 100
      AvailabilityZone: 
        !GetAtt OTCSADM.AvailabilityZone
  csefs: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 100
      AvailabilityZone: 
        !GetAtt OTCSADM.AvailabilityZone
  csindex: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 70
      AvailabilityZone: 
        !GetAtt OTCSADM.AvailabilityZone
  # cs-index-backup: 
  #   Type: "AWS::EC2::Volume"
  #   # Condition: CreateProdResources
  #   Properties: 
  #     Size: 100
  #     AvailabilityZone: 
  #       !GetAtt OTCSADM.AvailabilityZone
  # migration: 
  #   Type: "AWS::EC2::Volume"
  #   # Condition: CreateProdResources
  #   Properties: 
  #     Size: 100
  #     AvailabilityZone: 
  #       !GetAtt OTCSADM.AvailabilityZone







# Outputs: 
#   VolumeId: 
#     # Condition: CreateProdResources
#     Value: 
#       !Ref NewVolume
