AWSTemplateFormatVersion: "2010-09-09"
Mappings: 
  RegionMap: 
    us-east-1: 
      AMI: "ami-0e95e4dbc9cb6ac8d" # this is okram's AMI
      Az: "us-east-1a"
    us-west-2: 
      AMI: "ami-a0cfeed8"
      Az: "us-west-2a"
Parameters: 
  EnvType: 
    Description: Environment type.
    Default: DEV
    Type: String
    AllowedValues: 
      - PROD
      - UAT
      - TEST
      - DEV
    ConstraintDescription: must specify prod or test.
  VpcId:
    Type: String
    Description: "Id of the VPC to use"
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select atleast a private subnets in your selected VPC.
  Keyname:
    Type: String
    Description: "Name of the keypair"
    Default: ava-debug
  InstanceType:
    Type: String
    Description: "Name of the keypair"
    Default: m5d.xlarge

Resources:
  OTCSOTACSecurityGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/8
        # FromPort: 22
        IpProtocol: -1
        # ToPort: 22
      # - CidrIp: 0.0.0.0/0
      #   FromPort: 80
      #   IpProtocol: tcp
      #   ToPort: 80

  OTCSOTAC:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref Keyname
      SecurityGroupIds: 
        - !Ref OTCSOTACSecurityGrp
      SubnetId: !Select [0, !Ref SubnetIds]
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSOTAC, !Ref EnvType] ]
        -
          Key: App
          Value: AV2.0

  MountPoint1: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSOTAC
      VolumeId: 
        !Ref app
      Device: /dev/sdf

  app: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 60
      AvailabilityZone: 
        !GetAtt OTCSOTAC.AvailabilityZone
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSOTAC, !Ref EnvType, /dev/sdf]]
        -
          Key: App
          Value: AV2.0

  MountPoint2: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSOTAC
      VolumeId: 
        !Ref buffer
      Device: /dev/sdg

  buffer: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 200
      AvailabilityZone: 
        !GetAtt OTCSOTAC.AvailabilityZone
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSOTAC, !Ref EnvType, /dev/sdg]]
        -
          Key: App
          Value: AV2.0

  MountPoint3: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSOTAC
      VolumeId: 
        !Ref archieve
      Device: /dev/sdh

  archieve: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 2000
      Encrypted: True
      VolumeType: gp2
      AvailabilityZone: 
        !GetAtt OTCSOTAC.AvailabilityZone
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSOTAC, !Ref EnvType, /dev/sdh]]
        -
          Key: App
          Value: AV2.0

Outputs:
  OTCSOTACSecurityGrp:
    Value:
      !Ref OTCSOTACSecurityGrp
      
