AWSTemplateFormatVersion: "2010-09-09"
Mappings: 
  RegionMap: 
    us-east-1: 
      AMI: "ami-0e95e4dbc9cb6ac8d"
      Az: "us-east-1a"
    us-west-2: 
      AMI: "ami-a0cfeed8"
      Az: "us-west-2a"
Parameters: 
  EnvType: 
    Description: Environment type.
    Default: DEV
    Type: String
    AllowedValues: 
      - PROD
      - UAT
      - TEST
      - DEV
    ConstraintDescription: must specify prod or test.
  VpcId:
    Type: String
    Description: "Id of the VPC to use"
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select atleast two public subnets in your selected VPC for the ALB.
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Select 2 private subnets in your selected VPC.
  Keyname:
    Type: String
    Description: "Name of the keypair"
    Default: ava-debug
  InstanceType:
    Type: String
    Description: "Name of the keypair"
    Default: m5d.xlarge

Resources:
  OTCSFENSecurityGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 10.0.0.0/8
        IpProtocol: -1

  OTCSFEN01:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref Keyname
      SecurityGroupIds: 
        - !Ref OTCSFENSecurityGrp
      SubnetId: !Select [0, !Ref SubnetIds]
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSFEN01, !Ref EnvType] ]
        -
          Key: App
          Value: AV2.0

  MountPoint1: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSFEN01
      VolumeId: 
        !Ref appFEN1
      Device: /dev/sdf

  appFEN1: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 60
      AvailabilityZone: 
        !GetAtt OTCSFEN01.AvailabilityZone
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSFEN01, !Ref EnvType, /dev/sdf]]
        -
          Key: App
          Value: AV2.0

  OTCSFEN02:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref Keyname
      SecurityGroupIds: 
        - !Ref OTCSFENSecurityGrp
      SubnetId: !Select [1, !Ref SubnetIds]
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSFEN02, !Ref EnvType] ]
        -
          Key: App
          Value: AV2.0

  MountPointFEN2: 
    Type: "AWS::EC2::VolumeAttachment"
    Properties: 
      InstanceId: 
        !Ref OTCSFEN02
      VolumeId: 
        !Ref appFEN2
      Device: /dev/sdf

  appFEN2: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 60
      AvailabilityZone: 
        !GetAtt OTCSFEN02.AvailabilityZone
      Tags:
        -
          Key: Name
          Value: !Join [ '-', [OTCSFEN02, !Ref EnvType, /dev/sdf]]
        -
          Key: App
          Value: AV2.0

  FENEC2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200'
      Name: !Join [ '-', [FENEC2TargetGroup, !Ref EnvType]]
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      Targets:
      - Id:
          Ref: OTCSFEN01
        Port: 80
      - Id:
          Ref: OTCSFEN02
        Port: 80
      UnhealthyThresholdCount: 3
      VpcId:
        Ref: 'VpcId'
      Tags:
      - Key: App
        Value: AV2.0

  FENALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: FENEC2TargetGroup
      LoadBalancerArn:
          Ref: FENApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  FENApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join [ '-', [ OTAC-FEN-alb, !Ref Environment] ]
      Scheme: internet-facing # or internal
      Subnets: !Ref PublicSubnetIds
      SecurityGroups:
      - Ref: OTCSFENSecurityGrp
      Tags:
      - Key: App
        Value: AV2.0




Outputs:
  OTCSFENSecurityGrp:
    Value:
      !Ref OTCSFENSecurityGrp
      
